<a href="https://colab.research.google.com/github/prajwollamichhane11/Git-Commands/blob/master/Onsite_Session_Tasks_Oct_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tasks

In [0]:
import numpy as np

## Task 1: Normal Equation

### 1.1 Generate a `4x4` matrix.

Use random seed: `42`

In [3]:
np.random.seed(42)
x = np.random.random((4,4))
x

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

### 1.2 Slice out X and y

X is the first three columns, y is the last column

In [4]:
X = x[:,:3]
X

array([[0.37454012, 0.95071431, 0.73199394],
       [0.15601864, 0.15599452, 0.05808361],
       [0.60111501, 0.70807258, 0.02058449],
       [0.83244264, 0.21233911, 0.18182497]])

In [5]:
y = x[:,3:]
y

array([[0.59865848],
       [0.86617615],
       [0.96990985],
       [0.18340451]])

### 1.3 Implement normal equation

$ theta = (X^TX)^{-1}X^Ty$

In [6]:
from numpy import linalg
xt = np.transpose(X)
z = np.dot(xt,X)
a = np.linalg.inv(z)
b = np.dot(xt,y)
theta = np.dot(a,b)
theta

array([[ 0.14732513],
       [ 1.39096181],
       [-1.01032224]])

## Task 2. Computation Network

In this task, we'll build a computation network (just a series of computations) using numpy.

### 2.1 Generate the data

Generate (with random seed `42`):

- **`X`**: `6 x 2 x 2` random array
- **`W`**: `4 x 3` random array

In [7]:
np.random.seed(42)
X = np.random.random((6,2,2))
W = np.random.random((4,3))
X

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]],

       [[0.60111501, 0.70807258],
        [0.02058449, 0.96990985]],

       [[0.83244264, 0.21233911],
        [0.18182497, 0.18340451]],

       [[0.30424224, 0.52475643],
        [0.43194502, 0.29122914]],

       [[0.61185289, 0.13949386],
        [0.29214465, 0.36636184]]])

### 2.2 Reshape the data

Reshape $X$ to be `6 x 4`

In [9]:
X = X.reshape(6,4)
X

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184]])

### 2.3 Create a function named `linear` that accepts X, W, and b

Note: $b$ is just a number.

It should return $XW + b$.

In [14]:
def linear(X,W,b):
  return (np.dot(X,W)+b)

b = int(input())
linear(X,W,b)

5


array([[6.67248407, 6.56020334, 5.65051822],
       [6.00856359, 6.0612276 , 5.74239177],
       [6.57110525, 6.83153974, 5.93832878],
       [5.7733409 , 5.98751355, 5.33617193],
       [5.94737268, 5.90463428, 5.34865193],
       [5.87590672, 5.96663882, 5.44382095]])

### 2.4 Implement the softmax function

$$
\text{Softmax}(x_{i}) = \frac{\exp(x_i)}{\sum_j \exp(x_j)}
$$

It should take a vector and return a vector.


In [17]:
def softmax(X):
  return (np.exp(X))/(np.sum(np.exp(X), axis = 0))

softmax(X)

array([[0.14622638, 0.26235637, 0.25237032, 0.16822322],
       [0.11752305, 0.11850842, 0.12863606, 0.2198201 ],
       [0.18341124, 0.20583236, 0.12390165, 0.24384754],
       [0.23114807, 0.12537742, 0.14558041, 0.11105636],
       [0.13629996, 0.17135645, 0.18695139, 0.12370039],
       [0.1853913 , 0.11656899, 0.16256018, 0.13335239]])

### 2.5 Implement the cross entropy loss

$$ CE(y, \hat y) = -\sum_{i}y_{i}\log \hat y_{i} $$

It takes two vectors as inputs and returns a single number.

### 2.6 Combining Everything

Do 
$$z = XW +b \\ \hat y = softmax(z) \\ e = CE(y, \hat y)\\ pred = argmax_i \space \hat y_{i}$$

### 2.7 Save and read file

Save $X$, $W$ and $b$ to a file using `savez` and then read back the matrices and recreate the above metrics.

# Task 3: Confusion Matrix

#### Task 3.1 Set the random seed to 10

In [0]:
np.random.seed(10)

#### Task 3.2 Create two random arrays 'actual' and 'predicted' of size 100 only containing 0 and 1

In [19]:
actual = np.random.choice([0,1], size = 100)
actual
   

array([1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1])

In [20]:
predicted = np.random.choice([0,1], size = 100)
predicted

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

#### Task 3.3 Calculate True Positive (TP), True Negative (TN), False Positive (FP), False Negative (FN)

TP = Total number of times when value in actual array is 1 and corresponding value in predicted array is also 1.

TN = Total number of times when value in actual array is 0 and corresponding value in predicted array is also 0.

FP = Total number of times when value in actual array is 0 and corresponding value in predicted array is 1.

FN = Total number of times when value in actual array is 1 and corresponding value in predicted array is 0.



In [22]:
TP = np.sum(np.logical_and(predicted == 1, actual == 1))
TN = np.sum(np.logical_and(predicted == 0, actual == 0))
FP = np.sum(np.logical_and(predicted == 1, actual == 0))
FN = np.sum(np.logical_and(predicted == 0, actual == 1))

print(TP,TN, FP, FN)

24 29 26 21


#### 3.4 Calculate accuracy, recall, precision and f1-score.

* Accuracy = $\frac{TP+TN}{TP+FP+FN+TN}$ 
  
* Recall = $\frac{TP}{TP+FN}$
  
* Precision = $\frac{TP}{TP+FP}$
  
* F1 Score = 2$\frac{(Recall * Precision)}{(Recall + Precision)}$


In [23]:
Accuracy= (TP+TN)/(TP+FP+FN+TN)
Recall= TP/(TP+FN)
Precision= TP/(TP+FP)
F1Score= 2*((Recall*Precision)/(Recall+Precision))
F1Score

0.505263157894737